import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faCar,
  faFootballBall,
  faHeart,
  faPaw,
  faShoppingBag,
  faSmile,
  faStar,
  faTshirt,
  faUtensils,
} from "@fortawesome/free-solid-svg-icons";
export const emoticonesPersonnes = [
  // Heureux
  { nom: "sourire", icon: "😀" },
  { nom: "large_sourire", icon: "😁" },
  { nom: "joie", icon: "😂" },
  { nom: "souriant", icon: "😃" },
  { nom: "sourire", icon: "😄" },
  { nom: "rire", icon: "😆" },
  { nom: "satisfait", icon: "😆" },
  { nom: "innocent", icon: "😇" },
  { nom: "clin_d'œil", icon: "😉" },
  { nom: "rougir", icon: "😊" },
  { nom: "cœur_avec_des_étoiles", icon: "🥰" },
  { nom: "cœur_avec_des_étoiles", icon: "😍" },
  { nom: "satisfait", icon: "😋" },
  { nom: "soulagé", icon: "😌" },
  // Amoureux
  { nom: "bisou", icon: "😘" },
  { nom: "bisou_avec_sourire", icon: "😙" },
  { nom: "bisou_avec_les_yeux_fermés", icon: "😚" },
  { nom: "baiser", icon: "😗" },
  // Confus
  { nom: "confus", icon: "😕" },
  { nom: "perplexité", icon: "😖" },
  { nom: "déçu", icon: "😞" },
  { nom: "inquiet", icon: "😟" },
  // Triste
  { nom: "déçu", icon: "😢" },
  { nom: "pleurer", icon: "😭" },
  { nom: "persévérer", icon: "😣" },
  { nom: "déçu_et_soulagé", icon: "😥" },
  { nom: "visage_ouverte", icon: "😮" },
  { nom: "bâillon", icon: "🤐" },
  { nom: "bouche_cousue", icon: "🤐" },
  { nom: "chut", icon: "😯" },
  { nom: "endormi", icon: "😪" },
  { nom: "visage_fatigué", icon: "😫" },
  { nom: "dormir", icon: "😴" },
  // Mécontent
  { nom: "mécontent", icon: "😒" },
  { nom: "colère", icon: "😠" },
  { nom: "rage", icon: "😡" },
  { nom: "triomphe", icon: "😤" },
  { nom: "symboles_sur_la_bouche", icon: "🤬" },
  // Malade
  { nom: "masque", icon: "😷" },
  { nom: "thermomètre", icon: "🤒" },
  { nom: "pansement_sur_la_tête", icon: "🤕" },
  // Fatigué
  { nom: "fatigué", icon: "😩" },
  { nom: "sommeil", icon: "😴" },
  { nom: "zzz", icon: "💤" },
  // Effrayé
  { nom: "visage_vomissant", icon: "🤢" },
  { nom: "visage_en_sueur_froide", icon: "😓" },
  { nom: "visage_congelé", icon: "🥶" },
  // Famille
  { nom: "homme_et_garçon", icon: "👨‍👦" },
  { nom: "homme_et_garçon", icon: "👨‍👦" },
  { nom: "homme_et_fille", icon: "👨‍👧" },
  { nom: "homme_et_fille", icon: "👨‍👧" },
  { nom: "homme_avec_deux_enfants", icon: "👨‍👧‍👦" },
  { nom: "homme_avec_deux_enfants", icon: "👨‍👧‍👦" },
  { nom: "homme_avec_deux_enfants", icon: "👨‍👦‍👦" },
  { nom: "homme_avec_deux_enfants", icon: "👨‍👦‍👦" },
  { nom: "homme_avec_plusieurs_enfants", icon: "👨‍👧‍👧" },
  { nom: "homme_avec_plusieurs_enfants", icon: "👨‍👧‍👧" },
  { nom: "homme_avec_plusieurs_enfants", icon: "👨‍👦‍👦" },
  { nom: "homme_avec_plusieurs_enfants", icon: "👨‍👦‍👦" },
  // Profession
  { nom: "homme_docteur", icon: "👨‍⚕️" },
  { nom: "homme_pilote", icon: "👨‍✈️" },
  { nom: "homme_fermier", icon: "👨‍🌾" },
  { nom: "homme_cuisinier", icon: "👨‍🍳" },
  { nom: "homme_mécanicien", icon: "👨‍🔧" },
  { nom: "homme_technicien", icon: "👨‍🔬" },
  { nom: "homme_infirmier", icon: "👨‍⚕️" },
  { nom: "homme_scientifique", icon: "👨‍🔬" },
  { nom: "homme_étudiant", icon: "👨‍🎓" },
  { nom: "homme_artistique", icon: "👨‍🎨" },
  { nom: "homme_feu", icon: "👨‍🚒" },
  { nom: "homme_police", icon: "👮‍♂️" },
  { nom: "homme_police", icon: "👮‍♂️" },
  { nom: "homme_pompier", icon: "👨‍🚒" },
  { nom: "homme_opérateur", icon: "👨‍💼" },
  { nom: "homme_constructeur", icon: "👷‍♂️" },
  { nom: "homme_facteur", icon: "👨‍📬" },
  { nom: "homme_ouvrier", icon: "👨‍🏭" },
  { nom: "homme_ouvrier", icon: "👨‍🏭" },
  { nom: "homme_office", icon: "👨‍💻" },
  { nom: "homme_technologie", icon: "👨‍💼" },
  { nom: "homme_d'usine", icon: "👨‍🏭" },
  { nom: "homme_du_bâtiment", icon: "👨‍🔧" },
  // Hommes seuls
  { nom: "homme_arreté", icon: "🚶‍♂️" },
  { nom: "homme_arreté", icon: "🚶‍♂️" },
  { nom: "homme_qui_marche", icon: "🚶‍♂️" },
  { nom: "homme_qui_marche", icon: "🚶‍♂️" },
  { nom: "homme_qui_court", icon: "🏃‍♂️" },
  { nom: "homme_qui_court", icon: "🏃‍♂️" },
  // Couples
  { nom: "homme_et_femme_tenant_la_main", icon: "👫" },
  { nom: "homme_et_femme_tenant_la_main", icon: "👫" },
  { nom: "deux_hommes_tenant_la_main", icon: "👬" },
  { nom: "deux_hommes_tenant_la_main", icon: "👬" },
];
export const heartEmojis = [
  { name: "red_heart", icon: "❤️" },
  { name: "orange_heart", icon: "🧡" },
  { name: "yellow_heart", icon: "💛" },
  { name: "green_heart", icon: "💚" },
  { name: "blue_heart", icon: "💙" },
  { name: "purple_heart", icon: "💜" },
  { name: "brown_heart", icon: "🤎" },
  { name: "black_heart", icon: "🖤" },
  { name: "white_heart", icon: "🤍" },
  { name: "heart_with_arrow", icon: "💘" },
  { name: "heart_with_ribbon", icon: "💝" },
  { name: "sparkling_heart", icon: "💖" },
  { name: "growing_heart", icon: "💗" },
  { name: "beating_heart", icon: "💓" },
  { name: "broken_heart", icon: "💔" },
  { name: "heart_on_fire", icon: "❤️‍🔥" },
  { name: "mended_heart", icon: "❤️‍🩹" },
  { name: "heart_exclamation", icon: "❣️" },
  { name: "two_hearts", icon: "💕" },
  { name: "revolving_hearts", icon: "💞" },
  { name: "heart_decoration", icon: "💟" },
  { name: "heart_suit", icon: "♥️" },
  { name: "heart_with_arrow", icon: "💘" },
  { name: "heart_with_ribbon", icon: "💝" },
  { name: "heart_with_arrow", icon: "💘" },
  { name: "heart_with_ribbon", icon: "💝" },
];
export const handEmojis = [
  { name: "thumbs_up", icon: "👍" },
  { name: "thumbs_down", icon: "👎" },
  { name: "raised_fist", icon: "✊" },
  { name: "oncoming_fist", icon: "👊" },
  { name: "raised_hand", icon: "✋" },
  { name: "victory_hand", icon: "✌️" },
  { name: "crossed_fingers", icon: "🤞" },
  { name: "love_you_gesture", icon: "🤟" },
  { name: "sign_of_horns", icon: "🤘" },
  { name: "call_me_hand", icon: "🤙" },
  { name: "ok_hand", icon: "👌" },
  { name: "pinched_fingers", icon: "🤌" },
  { name: "pinching_hand", icon: "🤏" },
  { name: "vulcan_salute", icon: "🖖" },
  { nom: "clown", icon: "🤡" },
  { nom: "ogre_japonais", icon: "👹" },
  { nom: "gobelin_japonais", icon: "👺" },
  { nom: "fantôme", icon: "👻" },
  { nom: "alien", icon: "👽" },
  { nom: "envahisseur_de_l'espace", icon: "👾" },
  { nom: "robot", icon: "🤖" },
  { nom: "crâne", icon: "💀" },
  { nom: "crâne_et_os_croisés", icon: "☠️" },
  { nom: "flocon_de_neige", icon: "❄️" },
  { nom: "soleil", icon: "☀️" },
  { nom: "lune", icon: "🌙" },
  { nom: "étoile", icon: "⭐" },
  { nom: "éclair", icon: "⚡️" },
  { nom: "nuage", icon: "☁️" },
  { nom: "pluie", icon: "🌧️" },
  { nom: "arc-en-ciel", icon: "🌈" },
  { nom: "montagne", icon: "⛰️" },
  { nom: "volcan", icon: "🌋" },
  { nom: "île", icon: "🏝️" },
  { nom: "terre", icon: "🌍" },
  { nom: "globe_terrestre", icon: "🌐" },
  { nom: "étoile_filante", icon: "🌠" },
  { nom: "comète", icon: "☄️" },
  // Nature
  { nom: "arbre", icon: "🌳" },
  { nom: "fleur", icon: "🌸" },
  { nom: "fleur", icon: "💐" },
  { nom: "rose", icon: "🌹" },
  { nom: "tulipe", icon: "🌷" },
  { nom: "plante", icon: "🌱" },
  { nom: "feuille", icon: "🍃" },
  { nom: "feuille_d'érable", icon: "🍁" },
  { nom: "feuille_d'automne", icon: "🍂" },
];
export const emojiVoyageEtLieu = [
  // Moyens de transport
  { nom: "voiture", icon: "🚗" },
  { nom: "taxi", icon: "🚕" },
  { nom: "bus", icon: "🚌" },
  { nom: "tramway", icon: "🚋" },
  { nom: "train", icon: "🚆" },
  { nom: "métro", icon: "🚇" },
  { nom: "train_souterrain", icon: "🚇" },
  { nom: "train_a_haut_vitesse", icon: "🚄" },
  { nom: "train_bulet", icon: "🚅" },
  { nom: "train_a_double_étage", icon: "🚞" },
  { nom: "bateau", icon: "⛴️" },
  { nom: "navire", icon: "🚢" },
  { nom: "bateau_de_croisière", icon: "🛳️" },
  { nom: "avion", icon: "✈️" },
  { nom: "avion_de_ligne", icon: "🛫" },
  { nom: "avion_à_hélice", icon: "🛩️" },
  { nom: "avion_privé", icon: "🛬" },
  { nom: "hélicoptère", icon: "🚁" },
  { nom: "montgolfière", icon: "🎈" },
  { nom: "fusée", icon: "🚀" },
  // Lieux
  { nom: "maison", icon: "🏠" },
  { nom: "maison_avec_jardin", icon: "🏡" },
  { nom: "appartement", icon: "🏢" },
  { nom: "hôtel", icon: "🏨" },
  { nom: "motels", icon: "🏩" },
  { nom: "camping", icon: "🏕️" },
  { nom: "caravane", icon: "🚐" },
  { nom: "plage", icon: "🏖️" },
  { nom: "montagne", icon: "⛰️" },
  { nom: "campagne", icon: "🏞️" },
  { nom: "désert", icon: "🏜️" },
  { nom: "parc", icon: "🏞️" },
  { nom: "statue_de_la_liberté", icon: "🗽" },
  { nom: "mont_fuji", icon: "🗻" },
  { nom: "tente", icon: "⛺" },
  { nom: "usine", icon: "🏭" },
  { nom: "bâtiment_de_bureau", icon: "🏢" },
  { nom: "banque", icon: "🏦" },
  { nom: "supermarché", icon: "🏪" },
  { nom: "école", icon: "🏫" },
  { nom: "université", icon: "🏫" },
  { nom: "hôpital", icon: "🏥" },
  { nom: "poste", icon: "🏣" },
  { nom: "musée", icon: "🏛️" },
  { nom: "cinéma", icon: "🎦" },
  { nom: "théâtre", icon: "🎭" },
  { nom: "église", icon: "⛪" },
  { nom: "mosquée", icon: "🕌" },
  { nom: "synagogue", icon: "🕍" },
  { nom: "temple", icon: "🛕" },
  { nom: "château", icon: "🏰" },
  { nom: "stade", icon: "🏟️" },
  { nom: "usine", icon: "🏭" },
  { nom: "construction", icon: "🏗️" },
  { nom: "gare", icon: "🚉" },
  { nom: "aéroport", icon: "🛫" },
  { nom: "poste_de_pompiers", icon: "🚒" },
  { nom: "hôtel_de_ville", icon: "🏛️" },
];
export const emojiActivites = [
  // Sport
  { nom: "foot", icon: "⚽️" },
  { nom: "basket", icon: "🏀" },
  { nom: "baseball", icon: "⚾️" },
  { nom: "tennis", icon: "🎾" },
  { nom: "golf", icon: "⛳️" },
  { nom: "ping_pong", icon: "🏓" },
  { nom: "badminton", icon: "🏸" },
  { nom: "volleyball", icon: "🏐" },
  { nom: "football_américain", icon: "🏈" },
  { nom: "rugby", icon: "🏉" },
  { nom: "surf", icon: "🏄‍♂️" },
  { nom: "natation", icon: "🏊‍♂️" },
  { nom: "patinage", icon: "⛸️" },
  { nom: "ski", icon: "⛷️" },
  { nom: "snowboard", icon: "🏂" },
  { nom: "escalade", icon: "🧗‍♂️" },
  { nom: "vélo", icon: "🚴‍♂️" },
  { nom: "vélo_de_montagne", icon: "🚵‍♂️" },
  { nom: "course", icon: "🏃‍♂️" },
  { nom: "musculation", icon: "🏋️‍♂️" },
  { nom: "boxe", icon: "🥊" },
  { nom: "lutte", icon: "🤼‍♂️" },
  { nom: "arts_martiaux", icon: "🥋" },
  // Loisirs
  { nom: "pêche", icon: "🎣" },
  { nom: "camping", icon: "⛺️" },
  { nom: "randonnée", icon: "🥾" },
  { nom: "barbecue", icon: "🍖" },
  { nom: "cinéma", icon: "🎬" },
  { nom: "musique", icon: "🎵" },
  { nom: "concert", icon: "🎸" },
  { nom: "festival", icon: "🎪" },
  { nom: "théâtre", icon: "🎭" },
  { nom: "cirque", icon: "🎪" },
  { nom: "parc", icon: "🏞️" },
  { nom: "plage", icon: "🏖️" },
  { nom: "ski_nautique", icon: "🚤" },
  { nom: "kayak", icon: "🛶" },
  { nom: "rafting", icon: "⛰️" },
  { nom: "surf_des_neiges", icon: "🏄‍♂️" },
  { nom: "luge", icon: "🛷" },
  { nom: "astronomie", icon: "🔭" },
  { nom: "jeux_vidéo", icon: "🎮" },
  { nom: "lecture", icon: "📚" },
  { nom: "jardinage", icon: "🌱" },
  { nom: "cuisine", icon: "🍳" },
];
export const emojiNourritureBoissons = [
  // Fruits
  { nom: "pomme", icon: "🍎" },
  { nom: "banane", icon: "🍌" },
  { nom: "raisin", icon: "🍇" },
  { nom: "pastèque", icon: "🍉" },
  { nom: "fraise", icon: "🍓" },
  { nom: "citron", icon: "🍋" },
  { nom: "orange", icon: "🍊" },
  { nom: "ananas", icon: "🍍" },
  { nom: "cerise", icon: "🍒" },
  { nom: "pêche", icon: "🍑" },
  // Légumes
  { nom: "tomate", icon: "🍅" },
  { nom: "aubergine", icon: "🍆" },
  { nom: "poivron", icon: "🫑" },
  { nom: "concombre", icon: "🥒" },
  { nom: "carotte", icon: "🥕" },
  { nom: "brocoli", icon: "🥦" },
  { nom: "champignon", icon: "🍄" },
  { nom: "piment", icon: "🌶️" },
  // Plats principaux
  { nom: "hamburger", icon: "🍔" },
  { nom: "pizza", icon: "🍕" },
  { nom: "hot_dog", icon: "🌭" },
  { nom: "taco", icon: "🌮" },
  { nom: "burrito", icon: "🌯" },
  { nom: "nouilles", icon: "🍜" },
  { nom: "spaghetti", icon: "🍝" },
  { nom: "sushi", icon: "🍣" },
  { nom: "sandwich", icon: "🥪" },
  // Desserts
  { nom: "glace", icon: "🍨" },
  { nom: "gâteau", icon: "🍰" },
  { nom: "donut", icon: "🍩" },
  { nom: "cookie", icon: "🍪" },
  { nom: "bonbon", icon: "🍬" },
  { nom: "chocolat", icon: "🍫" },
  { nom: "barre_chocolatée", icon: "🍫" },
  { nom: "popcorn", icon: "🍿" },
  { nom: "caramel", icon: "🍮" },
  // Boissons
  { nom: "verre_de_lait", icon: "🥛" },
  { nom: "café", icon: "☕" },
  { nom: "thé", icon: "🍵" },
  { nom: "soda", icon: "🥤" },
  { nom: "bière", icon: "🍺" },
  { nom: "bière", icon: "🍻" },
  { nom: "vin", icon: "🍷" },
  { nom: "cocktail", icon: "🍹" },
  { nom: "tropical", icon: "🍹" },
  { nom: "bière", icon: "🍺" },
  { nom: "champagne", icon: "🍾" },
  { nom: "whisky", icon: "🥃" },
  // Autres
  { nom: "miel", icon: "🍯" },
];
export const emojiAnimauxNature = [
  // Animaux
  { nom: "chat", icon: "😺" },
  { nom: "chien", icon: "🐶" },
  { nom: "lapin", icon: "🐰" },
  { nom: "souris", icon: "🐭" },
  { nom: "hamster", icon: "🐹" },
  { nom: "cochon_d'inde", icon: "🐹" },
  { nom: "écureuil", icon: "🐿️" },
  { nom: "hérisson", icon: "🦔" },
  { nom: "ours", icon: "🐻" },
  { nom: "panda", icon: "🐼" },
  { nom: "koala", icon: "🐨" },
  { nom: "tigre", icon: "🐯" },
  { nom: "lion", icon: "🦁" },
  { nom: "léopard", icon: "🐆" },
  { nom: "cheval", icon: "🐴" },
  { nom: "vache", icon: "🐮" },
  { nom: "bouc", icon: "🐐" },
  { nom: "mouton", icon: "🐑" },
  { nom: "cochon", icon: "🐷" },
  { nom: "éléphant", icon: "🐘" },
  { nom: "rhinocéros", icon: "🦏" },
  { nom: "hippopotame", icon: "🦛" },
  { nom: "girafe", icon: "🦒" },
  { nom: "chameau", icon: "🐪" },
  { nom: "chien_guide", icon: "🦮" },
  { nom: "chien_service", icon: "🐕‍🦺" },
  { nom: "poule", icon: "🐔" },
  { nom: "poule", icon: "🐓" },
  { nom: "hibou", icon: "🦉" },
  { nom: "pigeon", icon: "🐦" },
  { nom: "canard", icon: "🦆" },
  { nom: "cygne", icon: "🦢" },
  { nom: "oiseau", icon: "🐤" },
  { nom: "oiseau", icon: "🐦" },
  { nom: "poussin", icon: "🐥" },
  { nom: "colombe", icon: "🕊️" },
  { nom: "perroquet", icon: "🦜" },
  { nom: "cigogne", icon: "🦩" },
  { nom: "papillon", icon: "🦋" },
  { nom: "coq", icon: "🐓" },
  { nom: "cancer", icon: "♋" },
  { nom: "scorpion", icon: "♏" },
  { nom: "poisson", icon: "🐟" },
  { nom: "poisson", icon: "🐠" },
  { nom: "poisson", icon: "🐡" },
  { nom: "poisson", icon: "🐟" },
  { nom: "poisson", icon: "🐠" },
  { nom: "baleine", icon: "🐋" },
  { nom: "dauphin", icon: "🐬" },
  { nom: "pieuvre", icon: "🐙" },
  { nom: "crabe", icon: "🦀" },
  { nom: "crevette", icon: "🦐" },
  { nom: "homard", icon: "🦞" },
  { nom: "calamar", icon: "🦑" },
];
export const emojiObjets = [
  { nom: "téléphone", icon: "📱" },
  { nom: "ordinateur", icon: "💻" },
  { nom: "clavier", icon: "⌨️" },
  { nom: "souris", icon: "🖱️" },
  { nom: "smartphone", icon: "📱" },
  { nom: "ordinateur_portable", icon: "💻" },
  { nom: "disque_du_monde", icon: "🌐" },
  { nom: "imprimante", icon: "🖨️" },
  { nom: "écouteurs", icon: "🎧" },
  { nom: "microphone", icon: "🎤" },
  { nom: "appareil_photo", icon: "📷" },
  { nom: "télévision", icon: "📺" },
  { nom: "radio", icon: "📻" },
  { nom: "haut-parleur", icon: "🔊" },
  { nom: "horloge", icon: "🕰️" },
  { nom: "montre", icon: "⌚" },
  { nom: "réveil", icon: "⏰" },
  { nom: "lampe", icon: "💡" },
  { nom: "ampoule", icon: "💡" },
  { nom: "outil", icon: "🛠️" },
  { nom: "marteau", icon: "🔨" },
  { nom: "clé", icon: "🔑" },
  { nom: "serrure", icon: "🔒" },
  { nom: "pinceau", icon: "🖌️" },
  { nom: "crayon", icon: "✏️" },
  { nom: "stylo", icon: "🖊️" },
  { nom: "ciseaux", icon: "✂️" },
  { nom: "carte", icon: "🗺️" },
  { nom: "journal", icon: "📰" },
  { nom: "livre", icon: "📚" },
  { nom: "cahier", icon: "📒" },
  { nom: "document", icon: "📄" },
  { nom: "porte-documents", icon: "💼" },
  { nom: "valise", icon: "🧳" },
  { nom: "sac", icon: "🎒" },
  { nom: "cadeau", icon: "🎁" },
  { nom: "coffre-fort", icon: "🗄️" },
  { nom: "pièce", icon: "🪙" },
  { nom: "billets_de_banque", icon: "💵" },
  { nom: "carte_de_crédit", icon: "💳" },
  { nom: "magnétoscope", icon: "📼" },
  { nom: "dvd", icon: "📀" },
  { nom: "cassette", icon: "📼" },
  { nom: "téléphone_fixe", icon: "☎️" },
  { nom: "fax", icon: "📠" },
  { nom: "télécommande", icon: "📱" },
  { nom: "microscope", icon: "🔬" },
  { nom: "télescope", icon: "🔭" },
  { nom: "brosse_à_dents", icon: "🪥" },
  { nom: "éponge", icon: "🧽" },
  { nom: "papier_toilette", icon: "🧻" },
  { nom: "serviette", icon: "🪒" },
  { nom: "feu", icon: "🔥" },
  { nom: "terre", icon: "🌍" },
  { nom: "globe", icon: "🌐" },
  { nom: "atome", icon: "⚛️" },
  { nom: "yin yang", icon: "☯️" },
  { nom: "paix", icon: "☮️" },
  { nom: "croissant", icon: "🥐" },
  { nom: "sablier", icon: "⌛" },
  { nom: "horloge", icon: "🕰️" },
  { nom: "bougie", icon: "🕯️" },
  { nom: "sphère", icon: "🔮" },
  { nom: "chapelet", icon: "📿" },
  { nom: "magnétique", icon: "🧲" },
  { nom: "thermomètre", icon: "🌡️" },
  { nom: "balance", icon: "⚖️" },
  { nom: "épée", icon: "⚔️" },
  { nom: "lanterne", icon: "🏮" },
  { nom: "cadenas", icon: "🔒" },
  { nom: "clé", icon: "🔑" },
  { nom: "parchemin", icon: "📜" },
  { nom: "livre", icon: "📖" },
  { nom: "trèfle", icon: "♣️" },
  { nom: "coffre-fort", icon: "🗄️" },
  { nom: "trophée", icon: "🏆" },
  { nom: "médaille", icon: "🎖️" },
  { nom: "bouclier", icon: "🛡️" },
  { nom: "bulle", icon: "💬" },
  { nom: "mégaphone", icon: "📣" },
  { nom: "sonnette", icon: "🔔" },
  { nom: "cloche", icon: "🔕" },
  { nom: "marteau", icon: "🔨" },
  { nom: "couteau", icon: "🔪" },
  { nom: "cuillère", icon: "🥄" },
  { nom: "fourchette", icon: "🍴" },
  { nom: "baguette magique", icon: "🪄" },
  { nom: "boule de cristal", icon: "🔮" },
];
export const emojiVetements = [
  { nom: "t-shirt", icon: "👕" },
  { nom: "chemise", icon: "👔" },
  { nom: "pull", icon: "🧥" },
  { nom: "costume", icon: "🕴️" },
  { nom: "robe", icon: "👗" },
  { nom: "short", icon: "🩳" },
  { nom: "pantalon", icon: "👖" },
  { nom: "slip", icon: "🩲" },
  { nom: "bikini", icon: "🩱" },
  { nom: "lingerie", icon: "🩱" },
  { nom: "chaussettes", icon: "🧦" },
  { nom: "chaussures", icon: "👟" },
  { nom: "baskets", icon: "👟" },
  { nom: "chaussures_de_course", icon: "👟" },
  { nom: "chaussures_de_ville", icon: "👞" },
  { nom: "chaussures_à_talons", icon: "👠" },
  { nom: "bottes", icon: "👢" },
  { nom: "sandales", icon: "👡" },
  { nom: "tongs", icon: "🩴" },
  { nom: "mocassins", icon: "👞" },
  { nom: "casquette", icon: "🧢" },
  { nom: "chapeau", icon: "🎩" },
  { nom: "bonnet", icon: "🧢" },
  { nom: "casque", icon: "⛑️" },
  { nom: "écharpe", icon: "🧣" },
  { nom: "gants", icon: "🧤" },
  { nom: "ceinture", icon: "🩲" },
  { nom: "cravate", icon: "👔" },
  { nom: "noeud_papillon", icon: "🎀" },
];

export const tabsLinks = [
  {
    title: "Emoticones et personnes",
    tab: emoticonesPersonnes,
    icon: <FontAwesomeIcon icon={faSmile} />,
  },
  {
    title: "Voyage et lieux",
    tab: emojiVoyageEtLieu,
    icon: <FontAwesomeIcon icon={faCar} />,
  },
  {
    title: "Nourritures et boissons",
    tab: emojiNourritureBoissons,
    icon: <FontAwesomeIcon icon={faUtensils} />,
  },
  {
    title: "Activités",
    tab: emojiActivites,
    icon: <FontAwesomeIcon icon={faFootballBall} />,
  },
  {
    title: "Animaux et nature",
    tab: emojiAnimauxNature,
    icon: <FontAwesomeIcon icon={faPaw} />,
  },
  {
    title: "Cœurs",
    tab: heartEmojis,
    icon: <FontAwesomeIcon icon={faHeart} />,
  },
  {
    title: "Objets",
    tab: emojiObjets,
    icon: <FontAwesomeIcon icon={faShoppingBag} />,
  },
  {
    title: "Vêtements",
    tab: emojiVetements,
    icon: <FontAwesomeIcon icon={faTshirt} />,
  },
  {
    title: "Autres",
    tab: handEmojis, // Utilisez handEmojis comme exemple pour les autres catégories
    icon: <FontAwesomeIcon icon={faStar} />, // Utilisez l'icône appropriée pour d'autres catégories
  },
];
